draw_text(10,10,"lastdir:" + string(lastdir))
draw_text(10,30,"hinput:" + string(hinput))
draw_text(10,50,"vinput:" + string(vinput))
draw_text(10,70,"angledif:" + string(angledif))
draw_text(10,90,"speed:" + string(speed))
draw_text(10,110,"stamina:"+string(stamina))
draw_text(10,130,"staminaTime:"+string(staminaTimer))
draw_text(10,150,"staminaExaust:"+string(staminaExaust))